"""FreeBSD platform provider (mounts, fstab, hostname, unmount)."""

from pathlib import Path
import os
from typing import List, Optional

from mocinha.core.errors import ExecutionError, VerificationError
from mocinha.core.events import EventPhase, EventStream
from mocinha.core.provider import ExecutionContext, ProviderContract
from mocinha.providers.base import (
    CommandRunner,
    remove_target_paths,
    verify_target_files,
    verify_target_paths_absent,
    write_target_files,
)


class FreeBSDPlatformProvider(ProviderContract):
    """FreeBSD platform lifecycle manager."""

    def __init__(self, name: str = "freebsd", event_stream: Optional[EventStream] = None) -> None:
        super().__init__(name=name, event_stream=event_stream)
        self.runner = CommandRunner(event_stream=self.events)

    def capabilities(self) -> List[str]:
        return ["platform", "freebsd"]

    def validate(self, context: ExecutionContext) -> None:
        import shutil
        if not shutil.which("mount"):
            raise ExecutionError(
                message="FreeBSD mount utility not found.",
                cause="mount binary is required for platform operations.",
                failed_operation="Validate FreeBSD mount utility",
            )
        if not shutil.which("umount"):
            raise ExecutionError(
                message="FreeBSD umount utility not found.",
                cause="umount binary is required for platform operations.",
                failed_operation="Validate FreeBSD umount utility",
            )

    def prepare(self, context: ExecutionContext) -> None:
        Path(context.target_mount).mkdir(parents=True, exist_ok=True)


    def mount_target(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        target_root.mkdir(parents=True, exist_ok=True)

        root_dev = context.target_partitions.get("root")
        if not root_dev:
            raise ExecutionError(
                message="Cannot mount target: FreeBSD root partition is unknown.",
                cause="Partition step did not register root device.",
                failed_operation="Mount FreeBSD root",
            )

        self.events.action(EventPhase.PREPARE, f"Mounting FreeBSD root {root_dev} -> {target_root}")
        self.runner.run(["mount", root_dev, str(target_root)], phase=EventPhase.PREPARE, check=True)

        if "esp" in context.target_partitions:
            esp_dev = context.target_partitions["esp"]
            esp_mount = target_root / "boot" / "efi"
            esp_mount.mkdir(parents=True, exist_ok=True)
            self.events.action(EventPhase.PREPARE, f"Mounting FreeBSD ESP {esp_dev} -> {esp_mount}")
            self.runner.run(["mount", "-t", "msdosfs", esp_dev, str(esp_mount)], phase=EventPhase.PREPARE, check=True)

    def generate_fstab(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        fstab_file = target_root / "etc" / "fstab"
        fstab_file.parent.mkdir(parents=True, exist_ok=True)

        self.events.action(EventPhase.CONFIGURE, f"Generating FreeBSD {fstab_file}")

        entries = ["# /etc/fstab generated by Mocinha Installer (FreeBSD)\n# Device                Mountpoint      FStype  Options Dump    Pass#\n"]
        if "root" in context.target_partitions:
            dev = context.target_partitions["root"]
            entries.append(f"{dev:<24} /               ufs     rw      1       1\n")
        if "esp" in context.target_partitions:
            dev = context.target_partitions["esp"]
            entries.append(f"{dev:<24} /boot/efi       msdosfs rw      2       2\n")

        fstab_file.write_text("".join(entries))

    def configure_hostname(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        hostname = context.metadata.get("hostname", "au-box")
        rc_conf = target_root / "etc" / "rc.conf"
        rc_conf.parent.mkdir(parents=True, exist_ok=True)

        lines = rc_conf.read_text().splitlines() if rc_conf.is_file() else []
        lines = [line for line in lines if not line.startswith("hostname=")]
        lines.append(f'hostname="{hostname}"')
        rc_conf.write_text("\n".join(lines) + "\n")

        hosts_file = target_root / "etc" / "hosts"
        hosts_content = (
            "::1                     localhost localhost.my.domain\n"
            "127.0.0.1               localhost localhost.my.domain\n"
            f"127.0.1.1               {hostname}\n"
        )
        hosts_file.write_text(hosts_content)

    def verify_mounted(self, context: ExecutionContext) -> None:
        mounts = {"root": Path(context.target_mount)}
        if "esp" in context.target_partitions:
            mounts["esp"] = Path(context.target_mount) / "boot" / "efi"
        for role, path in mounts.items():
            if not os.path.ismount(path):
                raise VerificationError(
                    message=f"FreeBSD target {role} filesystem is not mounted at {path}.",
                    cause="The mount command did not leave an active mount point.",
                    failed_operation=f"Verify FreeBSD {role} mount",
                    current_state=f"{path} is not a mount point",
                    possible_recovery="Check the mount output in the event log.",
                )
        self.events.info(EventPhase.VERIFY, f"FreeBSD target mounts verified: {[str(p) for p in mounts.values()]}")

    def verify_fstab(self, context: ExecutionContext) -> None:
        fstab_file = Path(context.target_mount) / "etc" / "fstab"
        if not fstab_file.is_file():
            raise VerificationError(
                message=f"FreeBSD fstab file missing at {fstab_file}.",
                cause="fstab generation did not write the file.",
                failed_operation="Verify FreeBSD target fstab",
                current_state="Missing /etc/fstab",
                possible_recovery="Re-run fstab generation step.",
            )
        entries = [line.split() for line in fstab_file.read_text().splitlines() if line.strip() and not line.startswith("#")]
        if not any(len(e) >= 2 and e[1] == "/" for e in entries):
            raise VerificationError(
                message="FreeBSD fstab has no root (/) entry.",
                cause="The generated fstab does not mount the root filesystem.",
                failed_operation="Verify FreeBSD fstab root entry",
                current_state=fstab_file.read_text().strip(),
                possible_recovery="Re-run fstab generation step.",
            )
        self.events.info(EventPhase.VERIFY, f"FreeBSD fstab verified ({len(entries)} entries).")

    def _unmount(self, context: ExecutionContext, strict: bool) -> None:
        target_root = Path(context.target_mount)
        self.events.action(EventPhase.CLEANUP, f"Unmounting FreeBSD target hierarchy at {target_root}")
        self.runner.run(["sync"], phase=EventPhase.CLEANUP, check=strict)
        esp_mount = target_root / "boot" / "efi"
        if os.path.ismount(esp_mount):
            self.runner.run(["umount", str(esp_mount)], phase=EventPhase.CLEANUP, check=strict)
        if os.path.ismount(target_root):
            self.runner.run(["umount", str(target_root)], phase=EventPhase.CLEANUP, check=strict)

    def unmount_target(self, context: ExecutionContext) -> None:
        self._unmount(context, strict=True)

    def verify_unmounted(self, context: ExecutionContext) -> None:
        if os.path.ismount(context.target_mount):
            raise VerificationError(
                message=f"FreeBSD target is still mounted at {context.target_mount}.",
                cause="umount did not release the target filesystem.",
                failed_operation="Verify FreeBSD target unmount",
                current_state=f"{context.target_mount} is still a mount point",
                possible_recovery="Check for processes holding files on the target (fstat).",
            )
        self.events.info(EventPhase.VERIFY, f"FreeBSD target unmounted from {context.target_mount}.")

    def remove_live_only_files(self, context: ExecutionContext) -> None:
        remove_target_paths(context.target_mount, context.metadata["live_only_files"], self.events)

    def verify_live_only_files_removed(self, context: ExecutionContext) -> None:
        verify_target_paths_absent(context.target_mount, context.metadata["live_only_files"], self.events)

    def write_target_files(self, context: ExecutionContext) -> None:
        write_target_files(context.target_mount, context.metadata["target_files"], self.events)

    def verify_target_files(self, context: ExecutionContext) -> None:
        verify_target_files(context.target_mount, context.metadata["target_files"], self.events)

    def verify_hostname(self, context: ExecutionContext) -> None:
        expected = context.metadata["hostname"]
        rc_conf = Path(context.target_mount) / "etc" / "rc.conf"
        lines = rc_conf.read_text().splitlines() if rc_conf.is_file() else []
        values = [line.split("=", 1)[1].strip('"') for line in lines if line.startswith("hostname=")]
        if values != [expected]:
            raise VerificationError(
                message=f"FreeBSD target hostname entries are {values}, expected [{expected!r}].",
                cause="/etc/rc.conf on the target does not set exactly the chosen hostname.",
                failed_operation="Verify FreeBSD target hostname",
                current_state=f"hostname= entries: {values}",
                possible_recovery="Re-run the hostname step.",
            )
        self.events.info(EventPhase.VERIFY, f"FreeBSD target hostname verified: {expected}")

    def apply(self, context: ExecutionContext) -> None:
        pass

    def verify(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        fstab_file = target_root / "etc" / "fstab"
        if not fstab_file.is_file():
            raise VerificationError(
                message=f"FreeBSD fstab file missing at {fstab_file}.",
                cause="Platform configuration did not generate /etc/fstab.",
                failed_operation="Verify FreeBSD target fstab",
                current_state="Missing /etc/fstab",
                possible_recovery="Re-run fstab generation step.",
            )
        self.events.info(EventPhase.VERIFY, "FreeBSD platform configuration verified (/etc/fstab).")

    def cleanup(self, context: ExecutionContext) -> None:
        # Best-effort on the failure path; the unmount step itself is strict.
        self._unmount(context, strict=False)

