"""FreeBSD platform provider (mounts, fstab, hostname, unmount)."""

from pathlib import Path
from typing import List, Optional

from mocinha.core.errors import ExecutionError, VerificationError
from mocinha.core.events import EventPhase, EventStream
from mocinha.core.provider import ExecutionContext, ProviderContract
from mocinha.providers.base import CommandRunner


class FreeBSDPlatformProvider(ProviderContract):
    """FreeBSD platform lifecycle manager."""

    def __init__(self, name: str = "freebsd", event_stream: Optional[EventStream] = None) -> None:
        super().__init__(name=name, event_stream=event_stream)
        self.runner = CommandRunner(event_stream=self.events)

    def capabilities(self) -> List[str]:
        return ["platform", "freebsd"]

    def validate(self, context: ExecutionContext) -> None:
        pass

    def mount_target(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        target_root.mkdir(parents=True, exist_ok=True)

        root_dev = context.target_partitions.get("root")
        if not root_dev:
            raise ExecutionError(
                message="Cannot mount target: FreeBSD root partition is unknown.",
                cause="Partition step did not register root device.",
                failed_operation="Mount FreeBSD root",
            )

        self.events.action(EventPhase.PREPARE, f"Mounting FreeBSD root {root_dev} -> {target_root}")
        self.runner.run(["mount", root_dev, str(target_root)], phase=EventPhase.PREPARE, check=True)

        if "esp" in context.target_partitions:
            esp_dev = context.target_partitions["esp"]
            esp_mount = target_root / "boot" / "efi"
            esp_mount.mkdir(parents=True, exist_ok=True)
            self.events.action(EventPhase.PREPARE, f"Mounting FreeBSD ESP {esp_dev} -> {esp_mount}")
            self.runner.run(["mount", "-t", "msdosfs", esp_dev, str(esp_mount)], phase=EventPhase.PREPARE, check=True)

    def generate_fstab(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        fstab_file = target_root / "etc" / "fstab"
        fstab_file.parent.mkdir(parents=True, exist_ok=True)

        self.events.action(EventPhase.CONFIGURE, f"Generating FreeBSD {fstab_file}")

        entries = ["# /etc/fstab generated by Mocinha Installer (FreeBSD)\n# Device                Mountpoint      FStype  Options Dump    Pass#\n"]
        if "root" in context.target_partitions:
            dev = context.target_partitions["root"]
            entries.append(f"{dev:<24} /               ufs     rw      1       1\n")
        if "esp" in context.target_partitions:
            dev = context.target_partitions["esp"]
            entries.append(f"{dev:<24} /boot/efi       msdosfs rw      2       2\n")

        fstab_file.write_text("".join(entries))

    def configure_hostname(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        hostname = context.metadata.get("hostname", "au-box")
        rc_conf = target_root / "etc" / "rc.conf"
        rc_conf.parent.mkdir(parents=True, exist_ok=True)

        existing = rc_conf.read_text() if rc_conf.is_file() else ""
        if 'hostname="' not in existing:
            with open(rc_conf, "a") as f:
                f.write(f'hostname="{hostname}"\n')

        hosts_file = target_root / "etc" / "hosts"
        hosts_content = (
            "::1                     localhost localhost.my.domain\n"
            "127.0.0.1               localhost localhost.my.domain\n"
            f"127.0.1.1               {hostname}\n"
        )
        hosts_file.write_text(hosts_content)

    def unmount_target(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        self.events.action(EventPhase.CLEANUP, f"Unmounting FreeBSD target hierarchy at {target_root}")
        self.runner.run(["sync"], phase=EventPhase.CLEANUP, check=False)
        if (target_root / "boot" / "efi").is_dir():
            self.runner.run(["umount", "-f", str(target_root / "boot" / "efi")], phase=EventPhase.CLEANUP, check=False)
        self.runner.run(["umount", "-f", str(target_root)], phase=EventPhase.CLEANUP, check=False)

    def apply(self, context: ExecutionContext) -> None:
        pass

    def verify(self, context: ExecutionContext) -> None:
        pass
