"""Platform provider for Linux (mounts, fstab, machine-id, unmount)."""

from pathlib import Path
from typing import List, Optional
import shutil

from mocinha.core.errors import ExecutionError, VerificationError
from mocinha.core.events import EventPhase, EventStream
from mocinha.core.provider import ExecutionContext, ProviderContract
from mocinha.providers.base import CommandRunner


class LinuxPlatformProvider(ProviderContract):
    """Linux platform lifecycle manager."""

    def __init__(self, name: str = "linux", event_stream: Optional[EventStream] = None) -> None:
        super().__init__(name=name, event_stream=event_stream)
        self.runner = CommandRunner(event_stream=self.events)

    def capabilities(self) -> List[str]:
        return ["platform", "linux"]

    def validate(self, context: ExecutionContext) -> None:
        pass

    def mount_target(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        target_root.mkdir(parents=True, exist_ok=True)

        root_dev = context.target_partitions.get("root")
        if not root_dev:
            raise ExecutionError(
                message="Cannot mount target: Root partition device is unknown.",
                cause="Partition step did not set target root partition in context.",
                failed_operation="Mount target root",
                possible_recovery="Verify storage partitioning step.",
            )

        self.events.action(EventPhase.PREPARE, f"Mounting root {root_dev} -> {target_root}")
        self.runner.run(["mount", root_dev, str(target_root)], phase=EventPhase.PREPARE, check=True)

        # Mount ESP at /boot if present
        if "esp" in context.target_partitions:
            esp_dev = context.target_partitions["esp"]
            esp_mount = target_root / "boot"
            esp_mount.mkdir(parents=True, exist_ok=True)
            self.events.action(EventPhase.PREPARE, f"Mounting ESP {esp_dev} -> {esp_mount}")
            self.runner.run(["mount", esp_dev, str(esp_mount)], phase=EventPhase.PREPARE, check=True)

    def generate_fstab(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        fstab_file = target_root / "etc" / "fstab"
        fstab_file.parent.mkdir(parents=True, exist_ok=True)

        self.events.action(EventPhase.CONFIGURE, f"Generating {fstab_file}")

        entries = ["# /etc/fstab generated by Mocinha Installer\n"]
        for role, dev in context.target_partitions.items():
            uuid = ""
            if shutil.which("blkid"):
                proc = self.runner.run(["blkid", "-s", "UUID", "-o", "value", dev], check=False)
                uuid = proc.stdout.strip()

            dev_id = f"UUID={uuid}" if uuid else dev
            if role == "root":
                entries.append(f"{dev_id:<42} /         ext4    rw,relatime    0 1\n")
            elif role == "esp":
                entries.append(f"{dev_id:<42} /boot     vfat    rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 2\n")

        fstab_file.write_text("".join(entries))

    def configure_hostname(self, context: ExecutionContext) -> None:
        target_root = Path(context.target_mount)
        etc_dir = target_root / "etc"
        etc_dir.mkdir(parents=True, exist_ok=True)
        hostname = context.metadata.get("hostname", "mocinha")
        (etc_dir / "hostname").write_text(f"{hostname}\n")
        hosts_file = etc_dir / "hosts"
        hosts_content = (
            "127.0.0.1   localhost\n"
            "::1         localhost\n"
            f"127.0.1.1   {hostname}.localdomain {hostname}\n"
        )
        hosts_file.write_text(hosts_content)

    def unmount_target(self, context: ExecutionContext) -> None:
        target_root = context.target_mount
        self.events.action(EventPhase.CLEANUP, f"Unmounting target hierarchy at {target_root}")
        # Sync disk caches
        self.runner.run(["sync"], phase=EventPhase.CLEANUP, check=False)
        # Unmount recursively
        self.runner.run(["umount", "-R", target_root], phase=EventPhase.CLEANUP, check=False)

    def apply(self, context: ExecutionContext) -> None:
        pass

    def verify(self, context: ExecutionContext) -> None:
        pass
