"""LILO bootloader provider, legacy BIOS (Slackware; a77ien).

Writes /etc/lilo.conf the way Slackware's liloconfig "simple" mode does with
the MBR destination -- global append line, `boot = <disk>`, compact,
the bitmap menu (/boot/slack.bmp, liloconfig's colours and layout), prompt,
timeout, change-rules/reset, vga = normal -- with one Linux entry for the
kernel and initrd the initramfs provider reported. Then the target's own
lilo installs it to the MBR (inside a chroot of the target).

Differences from liloconfig, on purpose: `disk = <disk> bios=0x80` for every
disk (liloconfig writes it for virtio disks only). LILO goes to the MBR of the
chosen disk, and the disk the BIOS boots is always BIOS drive 0x80 at that
moment; left to guess, lilo can map another disk to 0x80 on a machine with two
disks, and the boot stops with "Keytable read/checksum error" (seen on a
two-disk Lenovo Legion after a setup2hd install, 2026-10-11). The root filesystem is named by
UUID (root="UUID=...", resolved by the initrd) instead of a /dev name that can
change between boots; no Windows/other-Linux entries are probed; the
timeout comes from [boot].timeout when set (seconds; liloconfig: 120 s).
"""

from pathlib import Path
from typing import List, Optional

from mocinha.core.errors import ExecutionError, VerificationError
from mocinha.core.events import EventPhase, EventStream
from mocinha.core.provider import ExecutionContext, ProviderContract
from mocinha.providers.base import CommandRunner, read_blkid_uuid, run_in_target

DEFAULT_TIMEOUT_TENTHS = 1200        # liloconfig


def lilo_conf(disk: str, root_uuid: str, kernel: str, initrd: Optional[str], append: List[str],
              timeout_tenths: int, bitmap: bool) -> str:
    lines = ["# LILO configuration file", "# generated by Mocinha, following Slackware's liloconfig (simple, MBR)",
             "#", "# Start LILO global section", "# Append any additional kernel parameters:",
             f'append="{" ".join(append)}"', ""]
    # The disk whose MBR the BIOS reads is drive 0x80 when it boots from it
    lines.append(f"disk = {disk} bios=0x80" + (" max-partitions=7" if Path(disk).name.startswith("vd") else ""))
    lines += [f"boot = {disk}", "# This option loads the kernel and initrd much faster:", "compact", ""]
    if bitmap:
        lines += ["# Boot BMP Image.", "# Bitmap in BMP format: 640x480x8", "  bitmap = /boot/slack.bmp",
                  "  bmp-colors = 255,0,255,0,255,0", "  bmp-table = 60,6,1,16", "  bmp-timer = 65,27,0,255", ""]
    lines += ["# Wait until the timeout to boot (if commented out, boot the", "# first entry immediately):",
              "prompt", "# Timeout before the first entry boots, in tenths of a second:", f"timeout = {timeout_tenths}",
              "# Override dangerous defaults that rewrite the partition table:", "change-rules", "  reset",
              "# Normal VGA console", "vga = normal", "# End LILO global section", "",
              "# Linux bootable partition config begins", f"image = {kernel}"]
    if initrd:
        lines.append(f"  initrd = {initrd}")
    lines += [f'  root = "UUID={root_uuid}"', "  label = Linux",
              "  read-only  # Partitions should be mounted read-only for checking",
              "# Linux bootable partition config ends", ""]
    return "\n".join(lines)


class LiloBootProvider(ProviderContract):
    def __init__(self, name: str = "lilo", event_stream: Optional[EventStream] = None) -> None:
        super().__init__(name=name, event_stream=event_stream)
        self.runner = CommandRunner(event_stream=self.events)

    def capabilities(self) -> List[str]:
        return ["bootloader", "lilo"]

    def validate(self, context: ExecutionContext) -> None:
        if context.metadata["firmware"].upper() != "BIOS":
            raise ExecutionError(message="LILO only boots in legacy BIOS mode.",
                                 cause=f"Firmware is {context.metadata['firmware']}.",
                                 failed_operation="Validate LILO firmware compatibility",
                                 current_state="No disk has been modified.",
                                 possible_recovery="Choose the remaster's UEFI bootloader (e.g. ELILO).")
        if (context.metadata.get("partition_table") or "dos").lower() != "dos":
            raise ExecutionError(message="LILO is installed to the MBR of a DOS-partitioned disk.",
                                 cause=f"The plan uses partition_table={context.metadata.get('partition_table')!r}.",
                                 failed_operation="Validate LILO partition table",
                                 current_state="No disk has been modified.",
                                 possible_recovery='Remove partition_table from the manifest (DOS is the BIOS default) '
                                                   'or set it to "dos".')

    def _conf(self, context: ExecutionContext) -> str:
        root = Path(context.target_mount)
        entries = context.metadata.get("boot_entries") or []
        if not entries:
            raise ExecutionError(message="No kernel was reported for the LILO entry.",
                                 cause="The initramfs step publishes the kernel and initrd it prepared.",
                                 failed_operation="Configure LILO",
                                 possible_recovery="Declare an initramfs provider (e.g. geninitrd) in the manifest.")
        entry = entries[0]
        initrd = entry.get("initrd")
        if initrd and not (root / str(initrd).lstrip("/")).exists():
            initrd = None
        timeout = context.metadata.get("boot_timeout")
        return lilo_conf(context.target_disk, read_blkid_uuid(self.runner, context.target_partitions["root"]),
                         str(entry["kernel"]), initrd, list(context.metadata.get("kernel_args", [])),
                         DEFAULT_TIMEOUT_TENTHS if timeout is None else int(timeout) * 10,
                         (root / "boot" / "slack.bmp").is_file())

    def apply(self, context: ExecutionContext) -> None:
        root = Path(context.target_mount)
        if not any((root / d / "lilo").is_file() for d in ("sbin", "usr/sbin")):
            raise ExecutionError(message="lilo not found on the target.",
                                 cause="LILO is installed with the installed system's own lilo package.",
                                 failed_operation="Locate lilo on the target")
        conf = root / "etc" / "lilo.conf"
        self.events.action(EventPhase.BOOTLOADER, f"Writing /etc/lilo.conf (boot = {context.target_disk})")
        conf.write_text(self._conf(context))
        self.events.action(EventPhase.BOOTLOADER, f"Installing LILO to the MBR of {context.target_disk}")
        run_in_target(self.runner, str(root), ["lilo", "-v", "-C", "/etc/lilo.conf"], phase=EventPhase.BOOTLOADER)

    def verify(self, context: ExecutionContext) -> None:
        root = Path(context.target_mount)
        problems = []
        conf = root / "etc" / "lilo.conf"
        if not conf.is_file() or conf.read_text() != self._conf(context):
            problems.append("/etc/lilo.conf does not match the planned configuration")
        if not (root / "boot" / "map").is_file():
            problems.append("/boot/map (LILO's map file) is missing")
        with open(context.target_disk, "rb") as disk:
            mbr = disk.read(512)
        if mbr[6:10] != b"LILO":
            problems.append(f"no LILO signature in the MBR of {context.target_disk}")
        if problems:
            raise VerificationError(message="LILO is not installed as planned.", cause="; ".join(problems),
                                    failed_operation="Verify LILO",
                                    possible_recovery="Inspect the lilo -v output in the event log.")
        self.events.info(EventPhase.VERIFY, f"LILO verified on {context.target_disk}.")
